"""empty message

Revision ID: 24c474fc11e9
Revises: 
Create Date: 2020-11-10 20:38:16.885042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24c474fc11e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer', sa.Column('avg_cal', sa.Float(), nullable=True))
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'user', ['user_id'], unique=True)
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('consumer', 'avg_cal')
    # ### end Alembic commands ###
